spring:
  application:
    name: venta-service

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ventas?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

    open-in-view: false

resilience4j:
  circuitbreaker:
    instances:
      ventaService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        ignoreExceptions:
          - feign.FeignException.NotFound

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT:9191}